spring:
  application:
    name: WALLET-CLIENT
  main:
    allow-bean-definition-overriding: true
  #热部署配置
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  #数据库连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.255.139:3306/wxwz?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 55000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 55000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 55000

feign:
  hystrix:
    enabled: true


# 在admin中允许扫描项目信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS